language: node_js
node_js:
  - "node"
# script:
# - npm install
# - npm run tslint
# - npm run setup
# - npm run unit-test

# # public API changes check
# - npm run api-extractor-ci

# # circular references check
# - cd tests && npm i
# - node_modules/.bin/webpack --env.android
# - node_modules/.bin/webpack --env.ios
